### ISSUE TITLE
Writeload Analysis on a Sharded Cluster

### ISSUE THREAD

**Issue by santhoshsk1918** [Gobind03/mongolyser#23]
In a sharded cluster we do not get write load analysis as local database is not accessable from mongos

**Comment by karan9** [comment]
@Gobind03 @santhoshsk1918 - I think this is done now?

**Comment by Gobind03** [comment]
Yes

**Comment by Gobind03** [comment]
We are recommending to use the connection string of the replica set inside the sharded cluster that has to be analysed.
